services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_designer
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      # Volumen administrado interno de n8n para credenciales
      - n8n_local_data:/home/node/.n8n
      # Carpeta compartida local para el manejo de recursos
      - ./data/n8n_shared_data:/home/node/.n8n-files
    environment:
      - GENERIC_TIMEZONE=America/Quito
      - TZ=America/Quito
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
    networks:
      - n8n_stack_network

  renderer:
    build:
      context: ./python_renderer
      dockerfile: Dockerfile
    container_name: python_renderer
    restart: always
    volumes:
      - ./python_renderer:/app
      - ./data/n8n_shared_data:/home/node/.n8n-files
    command: python /app/render.py
    ports:
      - "8000:8000"
    environment:
      - LMSTUDIO_API_URL=${LMSTUDIO_API_URL}
      - LMSTUDIO_MODEL=${LMSTUDIO_MODEL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - n8n_stack_network

  redis:
    image: redis:7-alpine
    container_name: redis_local
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - n8n_stack_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: unless-stopped
    command:
      - "http"
      - "n8n_designer:5678"
      - "--domain=stonewall-bountiful-steep.ngrok-free.dev"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - n8n_stack_network
    depends_on:
      - n8n

networks:
  n8n_stack_network:
    name: n8n_shared_network
    driver: bridge

volumes:
  n8n_local_data: